INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Afghanistan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Albania', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Algeria', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Andorra', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Angola', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Argentina', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Armenia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Australia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Austria', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Azerbaijan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bahamas', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bahrain', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bangladesh', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Barbados', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Belarus', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Belgium', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Belize', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Benin', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bhutan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bolivia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bosnia and Herzegovina', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Botswana', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Brazil', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Brunei', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Bulgaria', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Burkina Faso', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Burundi', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Cabo Verde', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Cambodia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Cameroon', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Canada', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Central African Republic', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Chad', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Chile', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('China', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Colombia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Comoros', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Congo, Democratic Republic of the', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Congo, Republic of the', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Costa Rica', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Croatia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Cuba', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Cyprus', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Czech Republic', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Denmark', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Djibouti', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Dominica', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Dominican Republic', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Ecuador', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Egypt', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('El Salvador', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Equatorial Guinea', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Eritrea', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Estonia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Eswatini', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Ethiopia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Fiji', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Finland', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('France', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Gabon', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Gambia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Georgia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Germany', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Ghana', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Greece', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Grenada', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Guatemala', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Guinea', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Guinea-Bissau', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Guyana', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Haiti', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Honduras', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Hungary', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Iceland', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('India', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Indonesia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Iran', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Iraq', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Ireland', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Israel', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Italy', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Jamaica', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Japan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Jordan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kazakhstan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kenya', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kiribati', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Korea, North', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Korea, South', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kosovo', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kuwait', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Kyrgyzstan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Laos', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Latvia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Lebanon', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Lesotho', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Liberia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Libya', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Liechtenstein', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Lithuania', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Luxembourg', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Madagascar', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Malawi', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Malaysia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Maldives', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mali', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Malta', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Marshall Islands', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mauritania', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mauritius', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mexico', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Micronesia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Moldova', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Monaco', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mongolia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Montenegro', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Morocco', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Mozambique', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Myanmar', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Namibia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Nauru', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Nepal', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Netherlands', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('New Zealand', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Nicaragua', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Niger', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Nigeria', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('North Macedonia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Norway', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Oman', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Pakistan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Palau', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Panama', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Papua New Guinea', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Paraguay', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Peru', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Philippines', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Poland', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Portugal', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Qatar', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Romania', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Russia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Rwanda', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Saint Kitts and Nevis', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Saint Lucia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Saint Vincent and the Grenadines', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Samoa', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('San Marino', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Sao Tome and Principe', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Saudi Arabia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Senegal', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Serbia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Seychelles', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Sierra Leone', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Singapore', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Slovakia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Slovenia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Solomon Islands', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Somalia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('South Africa', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('South Sudan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Spain', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Sri Lanka', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Sudan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Suriname', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Sweden', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Switzerland', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Syria', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Taiwan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Tajikistan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Tanzania', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Thailand', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Timor-Leste', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Togo', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Tonga', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Trinidad and Tobago', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Tunisia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Turkey', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Turkmenistan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Tuvalu', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Uganda', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Ukraine', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('United Arab Emirates', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('United Kingdom', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('United States', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Uruguay', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Uzbekistan', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Vanuatu', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Vatican City', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Venezuela', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Vietnam', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Yemen', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Zambia', GETUTCDATE());
INSERT INTO dbo.Countries (Name, CreatedAt) VALUES ('Zimbabwe', GETUTCDATE());